export const IMG_PATHS = {
  HEADER_LOGO: './images/1p_logo.png',
  INTRO_BACKGROUND: './images/1p_bg.png',
  INTRO_KIDS: './images/1p_kids.png',
  INTRO_STAR: './images/1p_star.png',
  INTRO_LINE: './images/1p_line.png',
  BANNER_LOGO: '/images/2p_logo-animation.gif',
  LIVE_BACKGROUND: './images/3p_bg.png',
  LIVE_PAD: '/images/3p_pad.png',
  LIVE_VIDEO: './images/3p_live-video.mp4',
  READING_BOOK1: './images/4p_book_1.png',
  READING_BOOK2: './images/4p_book_2.png',
  READING_BOOK3: './images/4p_book_3.png',
  READING_CHECK1: './images/4p_check1.gif',
  READING_CHECK2: './images/4p_check2.gif',
  READING_CHECK3: './images/4p_check3.gif',
};
